services:
  backend:
    build: ./school-payments-backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./school-payments-backend/.env

  frontend:
    build: ./school-payments-frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=https://task-z1yc.onrender.com
 
    depends_on:
      - backend
